package com.markminisce.annotations;

import org.springframework.context.ApplicationEvent;
import org.springframework.context.ApplicationListener;
import org.springframework.stereotype.Component;

@Component
public class MyEventListener implements ApplicationListener {

	//listens to all events generated by spring framework. 
	public void onApplicationEvent(ApplicationEvent event) {
		System.out.println(event.toString());
	}
	
	

}
